procedure_test: False
randomize_trails: False
do_training: False
n_answers: 1 # number of answers per trial

screen_color: grey
text_color: black
text_size: 28

# stimulus
stimulus_pos: [0,125]
stimulus_size: [1200, 900]
answer_time: 120


# fixation point
fixation_size: 56
fixation_color: black
fixation_text: +
fixation_time: 0
fixation_pos: [0, 0]

# answers
answers_type: mouse # mouse, keyboard, or text

## for answers_type == mouse
answer_size: 56
answer_color: black
answer_symbols: {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8} # key is real answer, value is presented symbol
answer_pos: {1: [-150, -380], 2: [-50, -380], 3: [50, -380], 4: [150, -380],
             5: [-150, -480], 6: [-50, -480], 7: [50, -480], 8: [150, -480]}
answer_box_color: green
answer_box_width: 6
answer_box_size: 86
answer_fill_color: darkgrey

# for answers_type == keyboard
reaction_keys: ["1", "2", "3", "4", "5"]

# for answer_type == text
text_box_pos: [0, -250]
text_box_width: 110
text_box_height: 60
text_box_line_color: black
text_box_line_width: 1
text_box_fill_color: darkgrey

text_box_text_size: 40
text_box_text_color: black
text_box_text_type: integer # integer, letters, custom
text_box_accept_key: ["return"]
text_box_max_elem: 4

# if text_box_type == custom you can choose your on set of symbols
text_box_symbols: []

# show extra text during trial
extra_text_to_show: [] # [{pos: [-270, -250], color: black, size: 40, text: "wprowadź odpowiedź:"},
                       #  {pos: [450, -350], color: black, size: 30, text: "zatwierdź enter"}]

# wait
wait_time: 1.5
wait_jitter: 1

# feedback
fdbk_training: True
fdbk_experiment: False
fdbk_correct: Poprawna odpowiedź
fdbk_incorrect: Błędna odpowiedź
fdbk_no_answer: Brak odpowiedzi
fdbk_show_time: 2
fdbk_color: black
fdbk_size: 56

# clock
show_clock: false
clock_pos: [450, 350]
clock_size: 60
clock_show_time: 7

# timer
show_timer: true
timer_pos: [750, 400]
timer_color: black
timer_size: 60
